// <auto-generated />
using System;
using Assignment02EFCore.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment02EFCore.Migrations
{
    [DbContext(typeof(ITIDbContext))]
    [Migration("20251108111404_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TopId")
                        .HasColumnType("int")
                        .HasColumnName("TopId_FK");

                    b.HasKey("Id");

                    b.HasIndex("TopId");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Course_Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Evaluate")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("InstructorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Courses_Instructors", (string)null);
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("HiringDate")
                        .HasColumnType("date")
                        .HasAnnotation("datatype", "date");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId")
                        .IsUnique();

                    b.ToTable("Departments", "HR");
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Cairo");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DeptId_FK");

                    b.Property<decimal>("HourRate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[Salary] / 160");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Salary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(18000m);

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Instructors", (string)null);
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Cairo");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DeptId_FK");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Student_Course", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(2,2)");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Students_Courses", (string)null);
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Course", b =>
                {
                    b.HasOne("Assignment01EFCore.Data.Models.Topic", "topic")
                        .WithMany("courses")
                        .HasForeignKey("TopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("topic");
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Course_Instructor", b =>
                {
                    b.HasOne("Assignment01EFCore.Data.Models.Course", "course")
                        .WithMany("instructors_course")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Assignment01EFCore.Data.Models.Instructor", "instructor")
                        .WithMany("course_Instructors")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("instructor");
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Department", b =>
                {
                    b.HasOne("Assignment01EFCore.Data.Models.Instructor", "instructor")
                        .WithOne("department")
                        .HasForeignKey("Assignment01EFCore.Data.Models.Department", "InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("instructor");
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Instructor", b =>
                {
                    b.HasOne("Assignment01EFCore.Data.Models.Department", "departmentInclude")
                        .WithMany("instructors")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("departmentInclude");
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Student", b =>
                {
                    b.HasOne("Assignment01EFCore.Data.Models.Department", "department")
                        .WithMany("students")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Student_Course", b =>
                {
                    b.HasOne("Assignment01EFCore.Data.Models.Course", "course")
                        .WithMany("student_Courses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Assignment01EFCore.Data.Models.Student", "student")
                        .WithMany("student_Courses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("student");
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Course", b =>
                {
                    b.Navigation("instructors_course");

                    b.Navigation("student_Courses");
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Department", b =>
                {
                    b.Navigation("instructors");

                    b.Navigation("students");
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Instructor", b =>
                {
                    b.Navigation("course_Instructors");

                    b.Navigation("department");
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Student", b =>
                {
                    b.Navigation("student_Courses");
                });

            modelBuilder.Entity("Assignment01EFCore.Data.Models.Topic", b =>
                {
                    b.Navigation("courses");
                });
#pragma warning restore 612, 618
        }
    }
}
